### ISSUE TITLE
Markbot

### ISSUE THREAD

**Issue by hend0298** [hend0298/hide-show-responsively#1]
@thomasjbradley When I compare my site to the screenshots, they look the same but when I put it in Markbot, it's different and the images are all stretched out. Did I do something wrong or is Markbot glitching?

**Comment by thomasjbradley** [comment]
It’s possibly because you’re using `display: flex` in a few places. Remember that this week we aren’t using `flex`—so stick to `inline-block` and it’ll probably work better.

**Comment by hend0298** [comment]
@thomasjbradley Okay, thanks that fixed it. Now for the 320px, one of the images is showing up in Markbot but not in my browser. Do you know why?

**Comment by thomasjbradley** [comment]
It’s a slight bug in Markbot—but it’s such a unique situation. To work around it, use `:nth-child(4)` instead of `:last-child`. Know that last child was a good choice, but Markbot just has a bug.
